FROM docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#RUN sysctl -w vm.max_map_count=262144
#RUN /bin/elasticsearch/bin/plugin install jettro/elasticsearch-gui
#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install jettro/elasticsearch-gui

#CMD ["./bin/elasticsearch"]

